from SigProfilerExtractor import sigpro as sig
import matplotlib.pyplot as plt
import SigProfilerExtractor as spe_mod
import os
import csv
import numpy as np

"""
    Function taken from the cloned code.
    Generates a csv for signatures_no signatures under test_matrix_96_output.
"""
def run_matrix_96(signatures_no):
    data = sig.importdata("matrix")
    sig.sigProfilerExtractor(
        "matrix",
        "test_matrix_96_output",
        data,
        minimum_signatures=signatures_no,
        maximum_signatures=signatures_no,
        nmf_replicates=5,
        min_nmf_iterations=100,
        max_nmf_iterations=1000,
        nmf_test_conv=100,
    )


"""
    Append the results generated by the script to a new csv.
    This is done to obtain statistics for multiple signatures.
"""
def run_for_all_signature_numbers():
    output_file = 'aggregated_solutions.csv'
    with open(output_file, 'a') as final_csv:
        writer = csv.writer(final_csv)

        # Append header.
        with open("../../test_matrix_96_output/SBS96/All_solutions_stat.csv", 'r') as output_csv:
            reader = csv.reader(output_csv)
            writer.writerow(next(reader))

        # Iterate up until 15 signatures, to reproduce figure 2A.
        for i in range(1, 16):
            #
            run_matrix_96(signatures_no=i)

            with open("test_matrix_96_output/SBS96/All_solutions_stat.csv", 'r') as output_csv:
                reader = csv.reader(output_csv)

                next(reader, None)
                writer.writerow(next(reader))

    return output_file

"""
    Get the signatures number, stability and frobenius% from the csv.
"""
def get_csv_values(file):
    signatures = []
    stability = []
    frobenius = []

    with open(file, 'r') as data:
        reader = csv.reader(data)
        next(reader)

        for row in reader:
            signatures.append(int(row[0][:-1]))
            stability.append(float(row[1]))
            frobenius.append(float(row[9])/10)
        
    return (signatures, stability, frobenius)


"""
    Plot the lines according to the 3 variables, just like in the SigProfiler paper.
"""
def plot_lines(signatures, reproducibility, frobenius):
    fig, ax1 = plt.subplots()

    # Plot x-axis for signatures number
    ax1.set_xlabel('Number of mutational signatures')
    ax1.set_xticks(np.arange(1, 16, 1.0))

    # Plot line corresponding to signature reproducibility.
    color = 'tab:red'
    ax1.set_ylabel('Signature reproducibility', color=color)
    ax1.plot(signatures, reproducibility, color=color, marker='o', label='Signature reproducibility')
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.set_ylim(0.0, 1.05)
    ax1.set_xlim(1, 15)

    # Plot line corresponding to Frobenius reconstruction error.
    ax2 = ax1.twinx()
    color = 'tab:blue'
    ax2.set_ylabel('Frobenius reconstruction error', color=color)
    ax2.plot(signatures, frobenius, color=color, marker='s', label='Frobenius reconstruction error')
    ax2.tick_params(axis='y', labelcolor=color)

    plt.title('Mutational Signature Analysis')
    plt.tight_layout()

    plt.savefig("../figures/figure_2A.pdf")


if __name__ == "__main__":
    # Create a csv of multiple signatures
    # Comment this if you already have a csv and want to avoid more computation

    prompt = input("Recompute csv file (y/n): ")
    signatures_csv = None
    if prompt == "y":
        signatures_csv = run_for_all_signature_numbers()
    else:
        file_name = input("Input the file name:\n")
        signatures_csv = file_name

    
    # Get necessary values from the csv 
    signatures, reproducibility, frobenius = get_csv_values(signatures_csv)

    # Create a plot based on these values.
    plot_lines(signatures, reproducibility, frobenius)
    